name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setting up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip
    - name: Build (AArch64)
      run: |
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=aarch64-linux-android31-clang++ ./build.sh
        zip -r shrx-aarch64.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: shrx (AArch64)
        path: shrx-aarch64.zip
    - name: Build (ARMv7-A)
      run: |
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=armv7a-linux-androideabi31-clang++ ./build.sh
        zip -r shrx-armv7a.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: shrx (ARMv7-A)
        path: shrx-armv7a.zip
    - name: Build (i686)
      run: |
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=i686-linux-android31-clang++ ./build.sh
        zip -r shrx-i686.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: shrx (i686)
        path: shrx-i686.zip
    - name: Build (x86_64)
      run: |
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=x86_64-linux-android31-clang++ ./build.sh
        zip -r shrx-x86_64.zip META-INF system push.ps1 push.sh
    - uses: actions/upload-artifact@v1
      with:
        name: shrx (x86_64)
        path: shrx-x86_64.zip
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/alioth'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-alioth"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          shrx-aarch64.zip
          shrx-armv7a.zip
          shrx-i686.zip
          shrx-x86_64.zip
